#pragma once

enum PLAYERSTATE
{
	STATE_ATT, STATE_IDLE, STATE_WALK, STATE_HIT,
	STATE_JUMP, STATE_FALL, STATE_LAND, STATE_DEAD,
	STATE_ATTD, STATE_ATTU
};

enum Direction { DR_LEFT, DR_RIGHT };

enum SCENEID
{
	SCENE_LOGO, SCENE_MENU, SCENE_HELP, SCENE_STAGE1
	, SCENE_STAGE2, SCENE_CLEAR, SCENE_END
};
enum MONSTERTYPE
{
	BITTLE, BUG, FLY, HUSH, HUSHKNIGHT, BOSS
};

enum MONSTERSTATE
{
	ATTACK, IDLE, WALK
};
enum KEYTYPE
{
	KEY_C, KEY_X, KEY_LEFT, KEY_RIGHT, KEY_DOWN, KEY_UP,
};

